/*
CREACIÓN
MODIFICACION
    AÑADIR ELEMENTOS
    ELIMINAR ELEMENTOS
    ELIMINIAR CONJUNTOS
DIFERENCIA SIMETRICA
*/ 

/** CREACION DE CONJUNTOS
 * CONSTARA DE 2 PARTES
 *  1 CREAR EL CONJUNTO
 *  2 AÑADIR LOS ELEMENTOS
 * 
 */

function crear